# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YqhQF2oBuL5nLbKvxekdVh3ZSgVBV2As
"""

from apscheduler.schedulers.blocking import BlockScheduler
from bluestar import alert
sched=BlockingScheduler()
sched.add_job(alert,'interval',seconds=10)
sched.start()